/**
 * Serialize GOL chat messages to a downloadable Markdown string.
 *
 * Handles text messages, markdown content, and data cards (tables, charts,
 * numbers, lists, dicts). Hides internal IDs like player_api_id.
 */

const HIDDEN_COLUMNS = ['player_api_id']

function formatTable(columns, rows) {
  const visibleCols = columns
    .map((col, i) => ({ col, idx: i }))
    .filter(({ col }) => !HIDDEN_COLUMNS.includes(col))

  if (!visibleCols.length || !rows.length) return ''

  const header = '| ' + visibleCols.map(({ col }) => col).join(' | ') + ' |'
  const separator = '| ' + visibleCols.map(() => '---').join(' | ') + ' |'
  const body = rows.map(row =>
    '| ' + visibleCols.map(({ idx }) => {
      const cell = row[idx]
      if (cell == null) return '\u2013'
      return String(cell)
    }).join(' | ') + ' |'
  ).join('\n')

  return [header, separator, body].join('\n')
}

function formatDataCard(card) {
  const { type, payload } = card
  if (!payload) return ''

  // analysis_result — could be table, chart, number, list, dict
  if (type === 'analysis_result') {
    const { result_type, display, columns, rows, value, items, data, meta } = payload

    // Description line
    const desc = meta?.description ? `*${meta.description}*\n\n` : ''

    // Tables and charts (charts use the same columns/rows structure)
    if ((result_type === 'table' || display === 'bar_chart' || display === 'line_chart') && columns && rows) {
      return desc + formatTable(columns, rows)
    }

    // Scalar / number
    if (result_type === 'scalar' || display === 'number') {
      const label = columns?.[0]
      return desc + (label ? `**${label}:** ${value}` : `**${value}**`)
    }

    // List
    if (result_type === 'list' && items) {
      return desc + items.map((item, i) => `${i + 1}. ${item}`).join('\n')
    }

    // Dict
    if (result_type === 'dict' && data) {
      return desc + Object.entries(data)
        .map(([k, v]) => `- **${k}:** ${v ?? '\u2013'}`)
        .join('\n')
    }
  }

  return ''
}

export function exportChatAsMarkdown(messages) {
  const lines = []

  lines.push('# GOL Analytics Chat')
  lines.push(`*Exported ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}*`)
  lines.push('')
  lines.push('---')
  lines.push('')

  for (const msg of messages) {
    if (msg.role === 'user') {
      lines.push(`> **You:** ${msg.content}`)
      lines.push('')
    } else if (msg.role === 'assistant') {
      // Skip empty messages (tool call loading states)
      if (!msg.content && !msg.dataCards?.length) continue

      if (msg.content) {
        lines.push(msg.content)
        lines.push('')
      }

      if (msg.dataCards?.length) {
        for (const card of msg.dataCards) {
          const cardMd = formatDataCard(card)
          if (cardMd) {
            lines.push(cardMd)
            lines.push('')
          }
        }
      }
    }
  }

  lines.push('---')
  lines.push('*Generated by [The Academy Watch](https://theacademywatch.com) GOL Analytics*')

  return lines.join('\n')
}
