"""Faithful threshold/contour trace of the existing 600px LaunchBoot logo.

Run with the workspace .loan Python (Pillow/numpy/OpenCV already installed).
No artwork is designed here: connected components preserve the source seams.
"""
from pathlib import Path
import hashlib
import json
import cv2
import numpy as np
from PIL import Image

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / 'academy-watch-ios/AcademyWatch/Assets.xcassets/LaunchBoot.imageset/LaunchBoot@3x.png'
image = np.array(Image.open(SOURCE).convert('RGBA'))
# Swift extraction stores white artwork and black seam pixels; trace white ink.
mask = ((image[:, :, 3] >= 128) & (image[:, :, 0] >= 128)).astype('uint8')
count, labels, stats, _ = cv2.connectedComponentsWithStats(mask)
parts = {'wing': np.zeros_like(mask), 'body': np.zeros_like(mask), 'sole': np.zeros_like(mask)}
for label in range(1, count):
    x, y, width, height, area = stats[label]
    if area < 16:
        continue
    # Existing disconnected wing feathers lie wholly left of the collar seam.
    part = 'wing' if x + width < 250 and y < 200 else 'sole' if y == 327 else 'body'
    parts[part][labels == label] = 1

def trace(part):
    contours, _ = cv2.findContours(parts[part], cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
    paths = []
    for contour in contours:
        points = cv2.approxPolyDP(contour, 0.45, True).reshape(-1, 2)
        if len(points) < 3:
            continue
        paths.append('M' + 'L'.join(f'{x + .5:g} {y + .5:g}' for x, y in points) + 'Z')
    return ''.join(paths)

out = ROOT / 'academy-watch-frontend/src/lib/academy-watch-logo.js'
source_hash = hashlib.sha256(SOURCE.read_bytes()).hexdigest()
lines = [ '// Generated by scripts/trace-loader-logo.py from the existing LaunchBoot@3x.png.',
          '// Pixel-space contours only; preserve the brand seams, feathers, laces and studs.',
          f'export const LOGO_SOURCE_SHA256 = {json.dumps(source_hash)}',
          'export const LOGO_PATHS = Object.freeze({']
lines += [f'  {part}: {json.dumps(trace(part))},' for part in parts]
lines += ['})', '']
out.write_text('\n'.join(lines))
print(f'Traced {SOURCE.name} → {out.name}: {out.stat().st_size} bytes; source SHA256 {source_hash}')
