"""add loan_flags table

Revision ID: 5e4d3c2b1a90
Revises: 2f7a9c1d0eab
Create Date: 2025-08-07 12:05:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e4d3c2b1a90'
down_revision = '2f7a9c1d0eab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_api_id', sa.Integer(), nullable=False),
    sa.Column('primary_team_api_id', sa.Integer(), nullable=False),
    sa.Column('loan_team_api_id', sa.Integer(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loan_flags')
    # ### end Alembic commands ###


