"""initial schema

Revision ID: a6b48cba84ca
Revises: 
Create Date: 2025-08-06 16:40:54.685195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6b48cba84ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixtures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixture_id_api', sa.Integer(), nullable=False),
    sa.Column('date_utc', sa.DateTime(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('competition_name', sa.String(length=100), nullable=True),
    sa.Column('home_team_api_id', sa.Integer(), nullable=True),
    sa.Column('away_team_api_id', sa.Integer(), nullable=True),
    sa.Column('home_goals', sa.Integer(), nullable=True),
    sa.Column('away_goals', sa.Integer(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fixture_id_api')
    )
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('flag', sa.String(length=255), nullable=True),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('is_european_top_league', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id')
    )
    op.create_table('fixture_player_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('player_api_id', sa.Integer(), nullable=False),
    sa.Column('team_api_id', sa.Integer(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('yellows', sa.Integer(), nullable=True),
    sa.Column('reds', sa.Integer(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fixture_id', 'player_api_id', name='uq_fixture_player')
    )
    op.create_table('fixture_team_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('team_api_id', sa.Integer(), nullable=False),
    sa.Column('stats_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fixture_id', 'team_api_id', name='uq_fixture_team')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('founded', sa.Integer(), nullable=True),
    sa.Column('national', sa.Boolean(), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('venue_name', sa.String(length=100), nullable=True),
    sa.Column('venue_address', sa.String(length=255), nullable=True),
    sa.Column('venue_city', sa.String(length=50), nullable=True),
    sa.Column('venue_capacity', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'season', name='uq_team_id_season')
    )
    op.create_table('loaned_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('nationality', sa.String(length=50), nullable=True),
    sa.Column('primary_team_id', sa.Integer(), nullable=False),
    sa.Column('primary_team_name', sa.String(length=100), nullable=False),
    sa.Column('loan_team_id', sa.Integer(), nullable=False),
    sa.Column('loan_team_name', sa.String(length=100), nullable=False),
    sa.Column('team_ids', sa.String(length=255), nullable=True),
    sa.Column('window_key', sa.String(length=50), nullable=True),
    sa.Column('actual_loan_status', sa.String(length=50), nullable=True),
    sa.Column('legacy_parent_team_id', sa.Integer(), nullable=True),
    sa.Column('legacy_loan_team_id', sa.Integer(), nullable=True),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('appearances', sa.Integer(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('minutes_played', sa.Integer(), nullable=True),
    sa.Column('yellows', sa.Integer(), nullable=True),
    sa.Column('reds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['loan_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['primary_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('newsletters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('newsletter_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('structured_content', sa.Text(), nullable=True),
    sa.Column('week_start_date', sa.Date(), nullable=True),
    sa.Column('week_end_date', sa.Date(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('published_date', sa.DateTime(), nullable=True),
    sa.Column('email_sent', sa.Boolean(), nullable=True),
    sa.Column('email_sent_date', sa.DateTime(), nullable=True),
    sa.Column('subscriber_count', sa.Integer(), nullable=True),
    sa.Column('generated_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('preferred_frequency', sa.String(length=20), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('unsubscribe_token', sa.String(length=100), nullable=True),
    sa.Column('last_email_sent', sa.DateTime(), nullable=True),
    sa.Column('bounce_count', sa.Integer(), nullable=True),
    sa.Column('email_bounced', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unsubscribe_token')
    )
    op.create_table('weekly_loan_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_team_id', sa.Integer(), nullable=False),
    sa.Column('parent_team_api_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('week_end_date', sa.Date(), nullable=False),
    sa.Column('include_team_stats', sa.Boolean(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('meta_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_team_id', 'week_start_date', 'week_end_date', name='uq_weekly_parent_week')
    )
    op.create_table('weekly_loan_appearances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weekly_report_id', sa.Integer(), nullable=False),
    sa.Column('loaned_player_id', sa.Integer(), nullable=False),
    sa.Column('player_api_id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('team_api_id', sa.Integer(), nullable=False),
    sa.Column('appeared', sa.Boolean(), nullable=True),
    sa.Column('minutes', sa.Integer(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('yellows', sa.Integer(), nullable=True),
    sa.Column('reds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.ForeignKeyConstraint(['loaned_player_id'], ['loaned_players.id'], ),
    sa.ForeignKeyConstraint(['weekly_report_id'], ['weekly_loan_reports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('weekly_report_id', 'loaned_player_id', 'fixture_id', name='uq_week_player_fixture')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weekly_loan_appearances')
    op.drop_table('weekly_loan_reports')
    op.drop_table('user_subscriptions')
    op.drop_table('newsletters')
    op.drop_table('loaned_players')
    op.drop_table('teams')
    op.drop_table('fixture_team_stats')
    op.drop_table('fixture_player_stats')
    op.drop_table('leagues')
    op.drop_table('fixtures')
    # ### end Alembic commands ###
