"""Add journalist team assignment

Revision ID: b49cbe6e8267
Revises: a1b2c3d4e5f6
Create Date: 2025-11-21 20:06:59.599011

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b49cbe6e8267'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Only creating new tables we added
    op.create_table('journalist_team_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['user_accounts.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'team_id', name='uq_journalist_team_assignment')
    )

    # team_profiles was already created in an earlier migration (12e5f7c8d9ab).
    # Guard against re-creating it on environments that already have the table.
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if not inspector.has_table('team_profiles'):
        op.create_table('team_profiles',
        sa.Column('team_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=160), nullable=False),
        sa.Column('code', sa.String(length=20), nullable=True),
        sa.Column('country', sa.String(length=80), nullable=True),
        sa.Column('founded', sa.Integer(), nullable=True),
        sa.Column('is_national', sa.Boolean(), nullable=True),
        sa.Column('logo_url', sa.String(length=255), nullable=True),
        sa.Column('venue_id', sa.Integer(), nullable=True),
        sa.Column('venue_name', sa.String(length=160), nullable=True),
        sa.Column('venue_address', sa.String(length=255), nullable=True),
        sa.Column('venue_city', sa.String(length=120), nullable=True),
        sa.Column('venue_capacity', sa.Integer(), nullable=True),
        sa.Column('venue_surface', sa.String(length=80), nullable=True),
        sa.Column('venue_image', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('team_id')
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journalist_team_assignments')
    # Do not drop team_profiles here; it predates this migration and may be in use
    # ### end Alembic commands ###
