import { useState } from 'react'
import { Link } from 'react-router-dom'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { APIService } from '@/lib/api'
import { AdminPageHeader, SectionTitle } from '@/components/admin/ControlRoom'
import { B3Gate, useControlData, LoadState, DetailPanel, Fact, QuietEmpty, ReasonAction, Pagination, rowClass, splitClass, metaClass, stamp } from '@/components/admin/B3Control'

export function AdminPeople() { return <B3Gate flag="admin_people"><People /></B3Gate> }
function People() {
    const [search, setSearch] = useState('')
    const [role, setRole] = useState('all')
    const [offset, setOffset] = useState(0)
    const [selected, setSelected] = useState(null)
    const list = useControlData(`/admin/people?q=${encodeURIComponent(search)}&offset=${offset}&role=${role}`)
    const detail = useControlData(selected ? `/admin/people/${selected}` : null)
    const person = detail.data?.person
    return <div className="space-y-8"><AdminPageHeader eyebrow={`People${list.data ? ` · ${list.data.total} accounts` : ''}`} title="Everyone" accent="on the pitch" lede="Roles come from current claims, staff grants and scout verification." actions={<label className="w-full sm:w-72"><span className="sr-only">Search people</span><Input placeholder="Search name or email" value={search} onChange={event => { setSearch(event.target.value); setOffset(0) }} /></label>} />
        <div className="flex flex-wrap gap-2" aria-label="People filters">{['all', 'players', 'clubs', 'scouts', 'admins'].map(value => <Button key={value} variant={role === value ? 'default' : 'outline'} size="sm" aria-pressed={role === value} onClick={() => { setRole(value); setOffset(0); setSelected(null) }}>{value[0].toUpperCase() + value.slice(1)}</Button>)}</div>
        <div className={splitClass}><section className={selected ? 'hidden min-w-0 xl:block' : 'min-w-0'}><SectionTitle title="Accounts" /><LoadState {...list} />{list.data?.rows.map(row => <button key={row.id} className={`${rowClass} ${selected === row.id ? 'bg-gold/[0.07]' : ''}`} type="button" aria-pressed={selected === row.id} onClick={() => setSelected(row.id)}><span className="flex flex-wrap items-baseline justify-between gap-2"><span className="break-words text-base">{row.display_name}</span><span className={metaClass}>{row.account_status}</span></span><span className="mt-1 block break-all text-sm text-muted-dark">{row.email}</span><span className="mt-3 flex flex-wrap gap-2">{row.roles.map(role => <span key={role} className="rounded-full border border-hairline-dark px-2 py-1 font-mono text-[10px] uppercase tracking-wider text-gold">{role.replaceAll('_', ' ')}</span>)}</span></button>)}{list.data?.rows.length === 0 && <QuietEmpty>No accounts match this search.</QuietEmpty>}<Pagination data={list.data} offset={offset} setOffset={setOffset} /></section>
            <DetailPanel title="Account details">{selected && <button type="button" className="mb-4 text-sm underline xl:hidden" onClick={() => setSelected(null)}>Back to accounts</button>}{!selected && <QuietEmpty>Select an account to review its standing.</QuietEmpty>}<LoadState data={selected ? detail.data : {}} error={detail.error} />{person && <><h2 className="display break-words text-3xl">{person.display_name}</h2><p className="mb-5 mt-2 break-all text-sm text-muted-dark">{person.email}</p><Fact label="Joined">{stamp(person.created_at)}</Fact><Fact label="Last login">{stamp(person.last_login_at)}</Fact><Fact label="Standing">{person.account_status}</Fact><Fact label="Approved claims">{person.approved_claims}</Fact><Fact label="Scout verification">{person.scout_verification?.status || 'No verification'}</Fact>{person.programs.map(program => <Fact key={program.id} label="Club"><Link to="/admin/programs" className="underline">{program.name}</Link></Fact>)}{person.scout_verification && <Link to={`/admin/trust?tab=verifications&user=${person.id}`} className="mt-4 block text-sm underline">Review scout verification</Link>}<Link to="/admin/users" className="mt-4 block text-sm underline">Manage writer permissions</Link><ReasonAction key={person.id} label={person.account_status === 'suspended' ? 'Restore account' : 'Suspend account'} action={reason => APIService.adminControlAction(`/admin/users/${person.id}/${person.account_status === 'suspended' ? 'restore' : 'suspend'}`, { reason })} onDone={() => { list.reload(); detail.reload() }} /><p className="mt-4 text-xs leading-relaxed text-muted-dark">This view contains account metadata only. Private club notes, feedback and messages are reviewed through their reported case.</p><p className="mt-3 text-xs leading-relaxed text-muted-dark">People can export their own data from account settings.</p></>}</DetailPanel>
        </div></div>
}
