import { useState } from 'react'
import { Input } from '@/components/ui/input'
import { AdminPageHeader, SectionTitle, BigStat } from '@/components/admin/ControlRoom'
import { B3Gate, useControlData, LoadState, DetailPanel, Fact, QuietEmpty, Pagination, splitClass, metaClass, stamp } from '@/components/admin/B3Control'

const day = date => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`
const zeroDecimal = new Set(['BIF', 'CLP', 'DJF', 'GNF', 'JPY', 'KMF', 'KRW', 'MGA', 'PYG', 'RWF', 'VND', 'VUV', 'XAF', 'XOF', 'XPF'])
const money = (amount, currency) => new Intl.NumberFormat(undefined, { style: 'currency', currency }).format(amount / (zeroDecimal.has(currency) ? 1 : 100))
export function AdminBusiness() { return <B3Gate flag="admin_business"><Business /></B3Gate> }
function Business() {
    const [from, setFrom] = useState(() => day(new Date(new Date().getFullYear(), new Date().getMonth(), 1)))
    const [to, setTo] = useState(() => day(new Date()))
    const [offset, setOffset] = useState(0)
    const view = useControlData(`/admin/business/summary?from=${from}&to=${to}&offset=${offset}`)
    const data = view.data
    return <div className="space-y-8"><AdminPageHeader eyebrow="Business & data" title="The" accent="books, the switches" lede="Actual receipts and refunds, kept separate by currency." actions={<div className="flex w-full flex-wrap gap-3"><label className="min-w-0 flex-1 text-xs text-muted-dark">From<Input type="date" value={from} onChange={event => { setFrom(event.target.value); setOffset(0) }} className="mt-1" /></label><label className="min-w-0 flex-1 text-xs text-muted-dark">To<Input type="date" value={to} onChange={event => { setTo(event.target.value); setOffset(0) }} className="mt-1" /></label></div>} /><LoadState {...view} />
        {data && <><div className="flex flex-wrap gap-8 border-y border-hairline-dark py-6">{Object.entries(data.currencies).map(([currency, totals]) => <div key={currency} className="flex min-w-0 flex-wrap gap-6"><BigStat label={`${currency} money in`} value={money(totals.money_in_cents, currency)} /><BigStat label={`${currency} refunds`} value={money(totals.refunds_cents, currency)} /></div>)}<BigStat label="Active club subscriptions" value={data.paying_clubs} /><BigStat label="Past due club subscriptions" value={data.past_due_clubs ?? 0} /></div>
            <div className={splitClass}><section className="min-w-0"><SectionTitle title="Money in, money back" count="Via Stripe" />{data.rows.map(row => <div key={`${row.source}-${row.id}`} className="flex flex-wrap items-center justify-between gap-4 border-b border-hairline-dark py-4"><div className="min-w-0"><p className={metaClass}>{stamp(row.occurred_at)}</p><p className="mt-2 text-base">{row.product_code.replaceAll('_', ' ')} · {row.kind}</p><p className="mt-1 text-sm text-muted-dark">{row.scope_name || (row.scope_type === 'club_program' ? `Club ${row.scope_id}` : row.purchaser_user_id ? `Account ${row.purchaser_user_id}` : 'Unlinked payment')}</p></div><div className="flex flex-wrap items-center gap-4"><span className="display text-2xl">{row.kind === 'refund' ? '−' : ''}{money(row.amount_cents, row.currency)}</span>{row.stripe_url && <a href={row.stripe_url} target="_blank" rel="noopener noreferrer" className="rounded-full border border-hairline-dark px-4 py-2 text-sm">Review in Stripe</a>}</div></div>)}{data.rows.length === 0 && <QuietEmpty>No recorded cash movements in this date range.</QuietEmpty>}<Pagination data={data} offset={offset} setOffset={setOffset} /><p className="mt-5 text-xs leading-relaxed text-muted-dark">{data.coverage}</p></section>
                <DetailPanel title="Data switches"><p className="eyebrow mb-5">Data switches</p><Fact label="Football data">{data.freeze.api_football ? 'Frozen' : 'Running'}</Fact><Fact label="Newsletters configured">{data.freeze.newsletters_configured ? 'Frozen' : 'Running'}</Fact><Fact label="Newsletters effective">{data.freeze.newsletters_effective ? 'Frozen' : 'Running'}</Fact><p className="mt-4 text-sm leading-relaxed text-muted-dark">These states are controlled by deployment configuration. Freezing football data also freezes newsletters. Stored pages remain readable.</p><p className="mt-4 text-sm leading-relaxed text-muted-dark">Refunds are reviewed and issued in Stripe. Film Room credit returns are separate from cash refunds.</p><h2 className="display mb-3 mt-7 text-2xl">Deployment history</h2>{data.changes.map(change => <div key={change.deployment_id} className="border-t border-hairline-dark py-3 text-sm"><p className="break-all">{change.deployment_id}</p><p className="mt-1 text-xs text-muted-dark">{stamp(change.observed_at)} · football {change.api_football_frozen ? 'frozen' : 'running'} · newsletters {change.newsletters_effective_frozen ? 'frozen' : 'running'}</p></div>)}{data.changes.length === 0 && <QuietEmpty>No deployment observations recorded yet.</QuietEmpty>}</DetailPanel>
            </div></>}
    </div>
}
