import { useState } from 'react'
import { Link } from 'react-router-dom'
import { APIService } from '@/lib/api'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { AdminPageHeader, SectionTitle, BigStat } from '@/components/admin/ControlRoom'
import { B3Gate, ConfirmAction, useControlData, LoadState, DetailPanel, Fact, QuietEmpty, Pagination, rowClass, splitClass, metaClass, stamp } from '@/components/admin/B3Control'

export function AdminSafety() { return <B3Gate flag="admin_safety"><Safety /></B3Gate> }
function Safety() {
    const [offset, setOffset] = useState(0)
    const [programOffset, setProgramOffset] = useState(0)
    const [suppressionOffset, setSuppressionOffset] = useState(0)
    const [selected, setSelected] = useState(null)
    const [all, setAll] = useState(false)
    const [reason, setReason] = useState('')
    const [error, setError] = useState('')
    const [restoreReason, setRestoreReason] = useState('')
    const [restoreError, setRestoreError] = useState('')
    const [busy, setBusy] = useState(false)
    const [pending, setPending] = useState(null)
    const list = useControlData(`/admin/safety/cases?status=${all ? 'all' : 'open'}&offset=${offset}`)
    const detail = useControlData(selected ? `/admin/safety/cases/${selected}` : null)
    const inventory = useControlData(`/admin/safety/hidden?program_offset=${programOffset}&suppression_offset=${suppressionOffset}`)
    const incident = detail.data?.case
    async function act(action) {
        const restoring = action === 'restore'
        const setActionError = restoring ? setRestoreError : setError
        setActionError(''); setBusy(true)
        try { await APIService.adminControlAction(`/admin/safety/cases/${incident.id}/actions`, { action, reason: (restoring ? restoreReason : reason).trim(), version: incident.version }); if (restoring) setRestoreReason(''); else setReason(''); list.reload(); detail.reload(); inventory.reload() }
        catch (err) { setActionError(err.message || 'Could not save this action.') }
        finally { setBusy(false); setPending(null) }
    }
    return <div className="space-y-8"><AdminPageHeader eyebrow="Safeguarding" title="Keep the game" accent="safe" lede="Hide first, review the reported evidence, then record the decision." />
        <div className="grid gap-5 border-y border-hairline-dark py-6 sm:grid-cols-3"><BigStat label="Open cases" value={list.data?.open_count ?? '—'} /><BigStat label="First action overdue" value={list.data?.overdue_count ?? '—'} sub="First action due within 24 hours" subTone="warn" /><BigStat label="Active holds" value={list.data ? list.data.active_suppressions + list.data.hidden_programs : '—'} sub="Player suppressions and club holds" /></div>
        <div className={splitClass}><section className={selected ? 'hidden min-w-0 xl:block' : 'min-w-0'}><SectionTitle title="Cases" action={<Button variant="outline" size="sm" onClick={() => { setAll(!all); setOffset(0) }}>{all ? 'Open only' : 'Include closed'}</Button>} /><LoadState {...list} />{list.data?.rows.map(row => <button key={row.id} type="button" aria-pressed={selected === row.id} onClick={() => { setSelected(row.id); setReason(''); setError(''); setRestoreReason(''); setRestoreError('') }} className={`${rowClass} ${selected === row.id ? 'bg-gold/[0.07]' : ''}`}><span className="flex flex-wrap items-center justify-between gap-2"><span className="break-words">Case {row.id} · {row.target_name || row.target_type.replaceAll('_', ' ')}</span><span className={metaClass}>{row.hidden ? 'Hidden · ' : ''}{row.status}</span></span><span className="mt-2 block text-sm text-muted-dark">{stamp(row.received_at)}{row.overdue ? ' · First action overdue' : ''}</span></button>)}{list.data?.rows.length === 0 && <QuietEmpty>No cases in this view.</QuietEmpty>}<Pagination data={list.data} offset={offset} setOffset={setOffset} /></section>
            <DetailPanel title="Safeguarding case details">{selected && <button type="button" className="mb-4 text-sm underline xl:hidden" onClick={() => setSelected(null)}>Back to cases</button>}{!selected && <QuietEmpty>Select a case to review its evidence.</QuietEmpty>}<LoadState data={selected ? detail.data : {}} error={detail.error} />{incident && <><p className={metaClass}>Case {incident.id} · {incident.target_type.replaceAll('_', ' ')}</p><h2 className="display mb-5 mt-3 text-3xl">{incident.hidden ? 'Hidden while we review' : 'Review the request'}</h2><p className="whitespace-pre-wrap break-words text-sm leading-relaxed">{detail.data.evidence.statement || 'No statement supplied.'}</p><Fact label="Target">{incident.target_name || incident.target_id}</Fact><Fact label="First action due">{stamp(incident.first_action_due_at)}</Fact><Fact label="Status">{incident.status}</Fact><Fact label="Notification">{incident.notification_state.replaceAll('_', ' ')}</Fact>
                {incident.status !== 'closed' && <div className="mt-5 space-y-3"><label className="block text-sm">Reason for this case action<Input required maxLength={2000} value={reason} onChange={event => setReason(event.target.value)} className="mt-2" /></label><div className="flex flex-wrap gap-2">{[['hide', 'Hide now'], ['investigate', 'Investigate'], ['club_contact', 'Club contacted'], ['close', 'Close case']].map(([action, label]) => <Button key={action} variant={action === 'hide' ? 'destructive' : 'outline'} disabled={busy || !reason.trim()} onClick={() => ['hide', 'close'].includes(action) ? setPending([action, label]) : act(action)}>{label}</Button>)}</div>{error && <p role="alert" className="text-sm">{error}</p>}</div>}
                <ConfirmAction open={!!pending} label={pending?.[1]} target={`case ${incident.id} · ${incident.target_name || `${incident.target_type} ${incident.target_id}`}`} reason={pending?.[0] === 'restore' ? restoreReason : reason} warning={pending?.[0] === 'hide' && incident.target_type === 'showcase_content' ? "This hides the player's whole public page, including every clip." : undefined} busy={busy} onCancel={() => setPending(null)} onConfirm={() => act(pending[0])} />
                {incident.hidden && (incident.owns_hold || incident.hold_requested) && <div className="mt-5"><label className="block text-sm">Reason to restore the case hold<Input maxLength={2000} value={restoreReason} onChange={event => setRestoreReason(event.target.value)} /></label><Button className="mt-3" variant="outline" disabled={busy || !restoreReason.trim()} onClick={() => setPending(['restore', 'Restore case hold'])}>Restore case hold</Button>{restoreError && <p role="alert">{restoreError}</p>}</div>}
                <p className="mt-4 text-xs leading-relaxed text-muted-dark">{incident.hidden && !incident.owns_hold && (incident.hold_requested ? "Another moderation decision owns this hold. Restoring this case withdraws only its request; the shared hold stays in place. " : "Another moderation decision owns this hold. Review or lift it through the original moderation tool. ")}Closing records the decision and queues a notification where an account recipient is available. Holds stay in place until separately reviewed and lifted.</p><Link to="/admin/programs" className="mt-3 block text-sm underline">Review club holds</Link><Link to="/admin/trust?tab=reports" className="mt-3 block text-sm underline">Open existing report moderation</Link><h3 className="mb-3 mt-6 text-sm">Case history</h3>{detail.data.events.map(event => <Fact key={event.id} label={event.action.replaceAll('_', ' ')}><span>{stamp(event.created_at)}<span className="mt-1 block max-w-64 break-words text-xs text-muted-dark">{event.reason}</span></span></Fact>)}</>}</DetailPanel>
        </div><section><SectionTitle title="Hidden inventory" /><LoadState {...inventory} />{inventory.data && <div className="grid gap-5 sm:grid-cols-2"><div role="region" aria-label="Club holds inventory"><h3 className="mb-3 text-sm">Club holds · {inventory.data.program_total ?? inventory.data.programs.length} total</h3>{inventory.data.programs.map(program => <Fact key={program.id} label="Club hold">{program.name}</Fact>)}{inventory.data.programs.length === 0 && <QuietEmpty>No active club holds.</QuietEmpty>}<Pagination data={{ total: inventory.data.program_total, limit: inventory.data.limit }} offset={programOffset} setOffset={setProgramOffset} /></div><div role="region" aria-label="Player suppressions inventory"><h3 className="mb-3 text-sm">Player suppressions · {inventory.data.suppression_total ?? inventory.data.suppressions.length} total</h3>{inventory.data.suppressions.map(row => <Fact key={row.id} label={`Suppression ${row.id}`}>{row.player_name || 'Player name unavailable'}</Fact>)}{inventory.data.suppressions.length === 0 && <QuietEmpty>No active player suppressions.</QuietEmpty>}<Pagination data={{ total: inventory.data.suppression_total, limit: inventory.data.limit }} offset={suppressionOffset} setOffset={setSuppressionOffset} /></div></div>}</section><p className="rounded-[10px] border border-gold/30 p-5 text-sm leading-relaxed text-muted-dark">New public publication uses the shared adults-only rule. A complete audit of legacy public scout records is not available here. Guardian applications remain coming soon.</p>
    </div>
}
